server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/mentalink_db

app.cookie.secure=false

jwt.secret=troque-esse-valor-por-uma-string-bem-grande-e-secreta-1234567890
jwt.expiration-ms=86400000
